var SUBJECTS = [
    "Anthropology / Archaeology",
    "Art",
    "Biology",
    "Business / Marketing",
    "Business Administration",
    "Chemistry",
    "Computer Sciences",
    "Construction",
    "Cultural and Ethnic Studies",
    "Economics",
    "Electrical",
    "English",
    "Environmental Studies",
    "Geography",
    "History",
    "Journalism, Media Studies and Communication",
    "Occupational Safety and Health",
    "Philosophy",
    "Political Science",
    "Psychology",
    "Wastewater",
    "Welding",
    "Woodworking",
]

export default SUBJECTS;
